version: '3'
services:
  app_contexto: 
    build: base
    mem_limit: 512m
    ports :
      - "8080:8080"
    environment :
      DB_URL: jdbc:mysql://contexto_invest:3306/prueba?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on :
      contexto_invest:
          condition: service_healthy
          
  contexto_invest:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: prueba
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
        timeout: 10s
        retries: 10